# MRI - Deep learning solutions fot dementia Disease prediction

De acuerdo con la organización mundial de la salud la dementia es un término que engloba varias enfermedades que afectan la memoria, el pensamiento y la capacidad para realizar actividades cotidianas. Esta enfermedad empeora con el tiempo, relacionada a condiciones que destruyen las células nerviosas y dañan el cerebro, lo que conduce a al deterioro de funciones cognitivas. La detección de esta destrucción resulta relevante para la salud de los pacientes e influye en las mejoras a su calidad de vida. 

Las imágenes de resonancias magnéticas (RM) tienen un papel en el diagnóstico de la demencia, consiste en permitir el estudio de las estructuras cerebrales y cómo cambian con el tiempo. En este sentido, los cambios en el hipocampo, así como en las regiones frontal y parietal, son marcadores evidentes del progreso de la enfermedad hacia la demencia. 

La Iniciativa de Neuroimagen de la Enfermedad de Alzheimer (ADNI) es la colección más importante y extensa de información relacionada con el Alzheimer, que contiene diferentes tipos de imágenes, información genética, información demográfica, pruebas cognitivas y biomarcadores en líquido cefalorraquídeo.

Se propone técnicas de Deep Learning y Convolutional Neural Networks, para analizar si  []